/** Max travel between a finger landing and lifting for the gesture to count as a tap. */
const TAP_SLOP = 24;

export class Input {
  private down = new Set<string>();
  private just = new Set<string>();
  // Rolling buffer of recently typed letters, for edge://surf-style cheat codes.
  private typed = '';
  mouseX = 0;
  mouseY = 0;
  mouseDown = false;
  readonly touchCapable =
    (typeof navigator !== 'undefined' && navigator.maxTouchPoints > 0) ||
    (typeof window.matchMedia === 'function' && window.matchMedia('(pointer: coarse)').matches);
  private touches = new Map<number, { x: number; y: number; startX: number; startY: number }>();
  private primaryTouch: number | null = null;
  private tapped = false;

  get touchActive(): boolean {
    return this.primaryTouch !== null;
  }

  clearHeld(): void {
    this.down.clear();
    this.just.clear();
    this.mouseDown = false;
    this.touches.clear();
    this.primaryTouch = null;
    this.tapped = false;
  }

  constructor() {
    window.addEventListener('keydown', (e) => {
      if (e.target instanceof Element && e.target.closest('button') && (e.code === 'Enter' || e.code === 'Space')) return;
      if (
        ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Space', 'Tab'].includes(
          e.code,
        )
      ) {
        e.preventDefault();
      }
      if (!e.repeat) this.just.add(e.code);
      this.down.add(e.code);
      // Track single printable characters for typed cheat sequences.
      if (e.key.length === 1) {
        this.typed = (this.typed + e.key.toLowerCase()).slice(-24);
      }
    });
    window.addEventListener('keyup', (e) => this.down.delete(e.code));
    window.addEventListener('blur', () => {
      this.clearHeld();
    });
    window.addEventListener('mousemove', (e) => {
      this.mouseX = e.clientX;
      this.mouseY = e.clientY;
    });
    window.addEventListener('mousedown', (e) => {
      if (e.target instanceof Element && e.target.closest('button')) return;
      if (e.button === 0) this.mouseDown = true;
    });
    window.addEventListener('mouseup', (e) => {
      if (e.button === 0) this.mouseDown = false;
    });

    // A touch on the playfield acts like mouse steering without requiring the
    // saved mouse-steering option. The first finger aims and thrusts; holding a
    // second finger engages boost. Pointer events keep this multi-touch logic
    // separate from compatibility mouse events generated by mobile browsers.
    window.addEventListener('pointerdown', (e) => {
      if (e.pointerType !== 'touch') return;
      if (e.target instanceof Element && e.target.closest('button')) return;
      e.preventDefault();
      this.touches.set(e.pointerId, { x: e.clientX, y: e.clientY, startX: e.clientX, startY: e.clientY });
      if (this.primaryTouch === null) {
        this.primaryTouch = e.pointerId;
        this.mouseX = e.clientX;
        this.mouseY = e.clientY;
      }
    }, { passive: false });
    window.addEventListener('pointermove', (e) => {
      const touch = this.touches.get(e.pointerId);
      if (e.pointerType !== 'touch' || !touch) return;
      e.preventDefault();
      touch.x = e.clientX;
      touch.y = e.clientY;
      if (e.pointerId === this.primaryTouch) {
        this.mouseX = e.clientX;
        this.mouseY = e.clientY;
      }
    }, { passive: false });
    const releaseTouch = (e: PointerEvent, cancelled: boolean) => {
      const touch = this.touches.get(e.pointerId);
      if (e.pointerType !== 'touch' || !touch) return;
      e.preventDefault();
      // A clean lift close to where the finger landed is a tap, not steering.
      if (!cancelled && Math.hypot(e.clientX - touch.startX, e.clientY - touch.startY) <= TAP_SLOP) {
        this.tapped = true;
      }
      this.touches.delete(e.pointerId);
      if (e.pointerId !== this.primaryTouch) return;
      const next = this.touches.entries().next();
      if (next.done) {
        this.primaryTouch = null;
      } else {
        this.primaryTouch = next.value[0];
        this.mouseX = next.value[1].x;
        this.mouseY = next.value[1].y;
      }
    };
    window.addEventListener('pointerup', (e) => releaseTouch(e, false), { passive: false });
    window.addEventListener('pointercancel', (e) => releaseTouch(e, true), { passive: false });
  }

  get thrust(): boolean {
    return this.down.has('KeyW') || this.down.has('ArrowUp');
  }
  get reverse(): boolean {
    return this.down.has('KeyS') || this.down.has('ArrowDown');
  }
  get turn(): number {
    let t = 0;
    if (this.down.has('KeyA') || this.down.has('ArrowLeft')) t -= 1;
    if (this.down.has('KeyD') || this.down.has('ArrowRight')) t += 1;
    return t;
  }
  get boost(): boolean {
    return this.down.has('Space') || this.down.has('ShiftLeft') || this.touches.size > 1;
  }

  /**
   * edge://surf-style cheat entry: returns true once when the player has just
   * finished typing `word` on the keyboard, then clears the buffer so the same
   * word must be retyped to fire again.
   */
  consumeTyped(word: string): boolean {
    if (this.typed.endsWith(word)) {
      this.typed = '';
      return true;
    }
    return false;
  }

  /**
   * Edge-triggered: returns true once for a finger that tapped the playfield
   * (down and up in the same spot) since the last frame. Buttons swallow their
   * own touches, so this only fires for taps on the game itself.
   */
  consumeTap(): boolean {
    if (!this.tapped) return false;
    this.tapped = false;
    return true;
  }

  /** Edge-triggered: returns true once per physical key press. */
  justPressed(code: string): boolean {
    if (this.just.has(code)) {
      this.just.delete(code);
      return true;
    }
    return false;
  }

  endFrame(): void {
    this.just.clear();
    // An unconsumed tap must not linger into a later frame and fire there.
    this.tapped = false;
  }
}
